input_dir: ../data/input
output_dir: ../data/output

# set this to False to skip extracting prices from the EIA files
# set this to True to extract prices from files manually downloaded via https://www.eia.gov/outlooks/steo/outlook.php#issues2021
acquire: False

commod_ids:
    # Crude Oil
    WTIPUUS: "West Texas Intermediate Spot Average, Crude Oil"
    BREPUUS: "Brent Spot Average, Crude Oil"

    # Liquid Fuels - Refiner prices for resale
    MGWHUUS: "Gasoline, Liquid Fuels - Refiner prices for resale"
    DSWHUUS: "Diesel Fuel, Liquid Fuels - Refiner prices for resale"
    D2WHUUS: "Heating Oil, Liquid Fuels - Refiner prices for resale"

    # Liquid Fuels - Retail prices including Texas
    MGRARUS: "Gasoline Regular Grade, Liquid Fuels - Retail prices including Texas"
    MGEIAUS: "Gasoline All Grades, Liquid Fuels - Retail prices including Texas"
    DSRTUUS: "On-highway Diesel Fuel, Liquid Fuels - Retail prices including Texas"
    D2RCAUS: "Heating Oil, Liquid Fuels - Retail prices including Texas"

    # Natural Gas
    NGHHMCF: "Henry Hub Spot, Natural Gas"
    NGRCUUS: "Retail prices - Residential sector, Natural Gas"

    # Electricity
    ESRCUUS: "Retail prices - residential sector, Electricity"

eval_params:
  metrics:
    - mae  # mean abs. error
    - mse  # mean sq. error
    - rmse  # root mean square
    - mre  # max residual error

  time_horizons:  # Months
    - 1
    - 2
    - 3
    - 6
    - 9
    - 12
