input_dir: ../data/input
output_dir: ../data/output

acquire: False  # set this to False to skip extracting prices from the EIA files

commod_ids:
    # Crude Oil
    - WTIPUUS   # West Texas Intermediate Spot Average
    - BREPUUS   # Brent Spot Average

    # Liquid Fuels - Refiner prices for resale
    - MGWHUUS  # Gasoline
    - DSWHUUS  # Diesel Fuel
    - D2WHUUS  # Fuel Oil (labelled as Heating Oil)

    # Liquid Fuels - Retail prices including Texas
    - MGRARUS  # Gasoline Regular Grade
    - MGEIAUS  # Gasoline All Grades
    - DSRTUUS  # On-highway Diesel Fuel
    - D2RCAUS  # Heating Oil

    # Natural Gas
    - NGHHMCF  # Henry Hub Spot ($ per 1000 cubic feet)
    - NGRCUUS  # Retail prices - residential sector

    # Electricity
    - ESRCUUS  # Retail prices - residential sector

eval_params:
  metrics:
    - mae  # mean abs. error
    - mse  # mean sq. error
    - rmse  # root mean square
    - max_error  # max_error

  time_horizons:  # Months
    - 1
    - 2
    - 3
    - 6
    - 9
    - 12
